# ansible-playbook --user igor -i ./inventory.ini catch-error-ex1.yml
---
- name: "Error handling example #1"
  hosts: bern_vm1
  any_errors_fatal: true              # я не увидел разницы между true и false ...
  tasks:
    - name: Preconfig block
      become: true
      vars:
        ansible_become_password: "xx"   # incorrect pw
        # ansible_become_password: "x"    # correct pw
      block:
        - name: Create user
          ansible.builtin.user:
            name: ansibleuser
            state: present
          register: error
          ignore_errors: true   # вот это позволяет перейти к следующему таску несмотря на ошибку

        - name: Install curl
          ansible.builtin.apt:
            name: curl
            update-cache: true
          register: error
      rescue:
        - name: Catch error
          ansible.builtin.debug:
            var: error
      always:
        - name: Finalize
          ansible.builtin.debug:
            msg: "Rebooting"
...
