# ansible-playbook --user igor -i ./inventory.ini catch-error-ex2.yml
---
- name: "Error handling example #2"
  hosts: bern_vm1
  tasks:
    - name: Preconfig block
      block:
        - name: Fail on FAILED                    # noqa: no-changed-when
          ansible.builtin.command: echo "FAILED"
          register: command_result
          failed_when: "'FAILED' in command_result.stdout"

        - name: Echo next step
          ansible.builtin.command: echo "Next step"
          changed_when: false                     # решает проверку линта: no-changed-when

      rescue:
        - name: Catch error
          ansible.builtin.debug:
            var: error
      always:
        - name: Finalize
          ansible.builtin.debug:
            msg: "Rebooting"
...
